### ISSUE TITLE
Dimensional Potion effects

### ISSUE THREAD

**Issue by Divineaspect** [Trcx528/ITA#1]
Feature Request
Potion Effects on being by Dimension ID?
Then we could overheat in Atum (or other hot dimensions) when wearing hot armor, or fly in mystical dimensions when using the correct magical materials.

**Comment by Trcx528** [comment]
Added, will be available in next build.

**Comment by Trcx528** [comment]
Added in public build 0.1.2
http://minecraft.curseforge.com/mc-mods/228461-infinitely-tweakable-armor/files
